# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DayTags' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DayTags
  pod 'AppCenter/Crashes', '~> 1.4.0'
  pod 'AppCenter/Analytics', '~> 1.4.0'
  pod 'AppCenterReactNativeShared', '~> 1.3.0'

  

  platform :ios, '9.0'
  target 'DayTagsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DayTags-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DayTags-tvOS

  target 'DayTags-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
